version: "3"
services:
  database:
    image: "postgres:14-alpine"
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todolist"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  db:
    driver: local